from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
from timeit import default_timer as timer
import csv
import ast
from PyQt5.QtWidgets import QButtonGroup

class Ui_MainWindow(object):

    '''
    Establishes the ui elements
    '''

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 710)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

#setting font for all elements
        font = QtGui.QFont()

#top and bottom lines
        font.setPointSize(16)
        font.setWeight(50)

        self.line_top = QtWidgets.QFrame(self.centralwidget)
        self.line_top.setGeometry(QtCore.QRect(56, 40, 408, 41))
        self.line_top.setLineWidth(8)
        self.line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top.setObjectName("line_top")

        self.line_bottom = QtWidgets.QFrame(self.centralwidget)
        self.line_bottom.setGeometry(QtCore.QRect(56, 440, 408, 41))
        self.line_bottom.setLineWidth(8)
        self.line_bottom.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bottom.setObjectName("line_bottom")

#left and right lines
        font.setPointSize(20)
        font.setWeight(50)

        self.line_left = QtWidgets.QFrame(self.centralwidget)
        self.line_left.setGeometry(QtCore.QRect(30, 60, 61, 401))
        self.line_left.setLineWidth(8)
        self.line_left.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_left.setObjectName("line_left")

        self.line_right = QtWidgets.QFrame(self.centralwidget)
        self.line_right.setGeometry(QtCore.QRect(430, 60, 61, 401))
        self.line_right.setLineWidth(8)
        self.line_right.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_right.setObjectName("line_right")

#input numbers for board
        #setting the font for the input lines
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)

        self.pos0 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos0.setGeometry(QtCore.QRect(70, 70, 41, 41))
        self.pos0.setFont(font)
        self.pos0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos0.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos0.setObjectName("pos0")

        self.pos1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos1.setGeometry(QtCore.QRect(110, 70, 41, 41))
        self.pos1.setFont(font)
        self.pos1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos1.setObjectName("pos1")

        self.pos2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos2.setGeometry(QtCore.QRect(150, 70, 41, 41))
        self.pos2.setFont(font)
        self.pos2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos2.setObjectName("pos2")

        self.pos10 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos10.setGeometry(QtCore.QRect(70, 110, 41, 41))
        self.pos10.setFont(font)
        self.pos10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos10.setObjectName("pos10")

        self.pos20 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos20.setGeometry(QtCore.QRect(70, 150, 41, 41))
        self.pos20.setFont(font)
        self.pos20.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos20.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos20.setObjectName("pos20")

        self.pos12 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos12.setGeometry(QtCore.QRect(150, 110, 41, 41))
        self.pos12.setFont(font)
        self.pos12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos12.setObjectName("pos12")

        self.pos22 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos22.setGeometry(QtCore.QRect(150, 150, 41, 41))
        self.pos22.setFont(font)
        self.pos22.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos22.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos22.setObjectName("pos22")

        self.pos21 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos21.setGeometry(QtCore.QRect(110, 150, 41, 41))
        self.pos21.setFont(font)
        self.pos21.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos21.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos21.setObjectName("pos21")

        self.pos11 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos11.setGeometry(QtCore.QRect(110, 110, 41, 41))
        self.pos11.setFont(font)
        self.pos11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos11.setObjectName("pos11")

        self.pos51 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos51.setGeometry(QtCore.QRect(110, 280, 41, 41))
        self.pos51.setFont(font)
        self.pos51.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos51.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos51.setObjectName("pos51")

        self.pos41 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos41.setGeometry(QtCore.QRect(110, 240, 41, 41))
        self.pos41.setFont(font)
        self.pos41.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos41.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos41.setObjectName("pos41")

        self.pos40 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos40.setGeometry(QtCore.QRect(70, 240, 41, 41))
        self.pos40.setFont(font)
        self.pos40.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos40.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos40.setObjectName("pos40")

        self.pos50 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos50.setGeometry(QtCore.QRect(70, 280, 41, 41))
        self.pos50.setFont(font)
        self.pos50.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos50.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos50.setObjectName("pos50")

        self.pos52 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos52.setGeometry(QtCore.QRect(150, 280, 41, 41))
        self.pos52.setFont(font)
        self.pos52.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos52.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos52.setObjectName("pos52")

        self.pos32 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos32.setGeometry(QtCore.QRect(150, 200, 41, 41))
        self.pos32.setFont(font)
        self.pos32.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos32.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos32.setObjectName("pos32")

        self.pos30 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos30.setGeometry(QtCore.QRect(70, 200, 41, 41))
        self.pos30.setFont(font)
        self.pos30.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos30.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos30.setObjectName("pos30")

        self.pos42 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos42.setGeometry(QtCore.QRect(150, 240, 41, 41))
        self.pos42.setFont(font)
        self.pos42.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos42.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos42.setObjectName("pos42")

        self.pos31 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos31.setGeometry(QtCore.QRect(110, 200, 41, 41))
        self.pos31.setFont(font)
        self.pos31.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos31.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos31.setObjectName("pos31")

        self.pos24 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos24.setGeometry(QtCore.QRect(240, 150, 41, 41))
        self.pos24.setFont(font)
        self.pos24.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos24.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos24.setObjectName("pos24")

        self.pos14 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos14.setGeometry(QtCore.QRect(240, 110, 41, 41))
        self.pos14.setFont(font)
        self.pos14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos14.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos14.setObjectName("pos14")

        self.pos13 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos13.setGeometry(QtCore.QRect(200, 110, 41, 41))
        self.pos13.setFont(font)
        self.pos13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos13.setObjectName("pos13")

        self.pos23 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos23.setGeometry(QtCore.QRect(200, 150, 41, 41))
        self.pos23.setFont(font)
        self.pos23.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos23.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos23.setObjectName("pos23")

        self.pos25 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos25.setGeometry(QtCore.QRect(280, 150, 41, 41))
        self.pos25.setFont(font)
        self.pos25.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos25.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos25.setObjectName("pos25")

        self.pos5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos5.setGeometry(QtCore.QRect(280, 70, 41, 41))
        self.pos5.setFont(font)
        self.pos5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos5.setObjectName("pos5")

        self.pos3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos3.setGeometry(QtCore.QRect(200, 70, 41, 41))
        self.pos3.setFont(font)
        self.pos3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos3.setObjectName("pos3")

        self.pos15 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos15.setGeometry(QtCore.QRect(280, 110, 41, 41))
        self.pos15.setFont(font)
        self.pos15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos15.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos15.setObjectName("pos15")

        self.pos4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos4.setGeometry(QtCore.QRect(240, 70, 41, 41))
        self.pos4.setFont(font)
        self.pos4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos4.setObjectName("pos4")

        self.pos16 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos16.setGeometry(QtCore.QRect(330, 110, 41, 41))
        self.pos16.setFont(font)
        self.pos16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos16.setObjectName("pos16")

        self.pos18 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos18.setGeometry(QtCore.QRect(410, 110, 41, 41))
        self.pos18.setFont(font)
        self.pos18.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos18.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos18.setObjectName("pos18")

        self.pos8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos8.setGeometry(QtCore.QRect(410, 70, 41, 41))
        self.pos8.setFont(font)
        self.pos8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos8.setObjectName("pos8")

        self.pos6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos6.setGeometry(QtCore.QRect(330, 70, 41, 41))
        self.pos6.setFont(font)
        self.pos6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos6.setObjectName("pos6")

        self.pos27 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos27.setGeometry(QtCore.QRect(370, 150, 41, 41))
        self.pos27.setFont(font)
        self.pos27.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos27.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos27.setObjectName("pos27")

        self.pos26 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos26.setGeometry(QtCore.QRect(330, 150, 41, 41))
        self.pos26.setFont(font)
        self.pos26.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos26.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos26.setObjectName("pos26")

        self.pos28 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos28.setGeometry(QtCore.QRect(410, 150, 41, 41))
        self.pos28.setFont(font)
        self.pos28.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos28.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos28.setObjectName("pos28")

        self.pos7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos7.setGeometry(QtCore.QRect(370, 70, 41, 41))
        self.pos7.setFont(font)
        self.pos7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos7.setObjectName("pos7")

        self.pos17 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos17.setGeometry(QtCore.QRect(370, 110, 41, 41))
        self.pos17.setFont(font)
        self.pos17.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos17.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos17.setObjectName("pos17")

        self.pos43 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos43.setGeometry(QtCore.QRect(200, 240, 41, 41))
        self.pos43.setFont(font)
        self.pos43.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos43.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos43.setObjectName("pos43")

        self.pos45 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos45.setGeometry(QtCore.QRect(280, 240, 41, 41))
        self.pos45.setFont(font)
        self.pos45.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos45.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos45.setObjectName("pos45")

        self.pos35 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos35.setGeometry(QtCore.QRect(280, 200, 41, 41))
        self.pos35.setFont(font)
        self.pos35.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos35.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos35.setObjectName("pos35")

        self.pos33 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos33.setGeometry(QtCore.QRect(200, 200, 41, 41))
        self.pos33.setFont(font)
        self.pos33.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos33.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos33.setObjectName("pos33")

        self.pos54 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos54.setGeometry(QtCore.QRect(240, 280, 41, 41))
        self.pos54.setFont(font)
        self.pos54.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos54.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos54.setObjectName("pos54")

        self.pos53 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos53.setGeometry(QtCore.QRect(200, 280, 41, 41))
        self.pos53.setFont(font)
        self.pos53.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos53.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos53.setObjectName("pos53")

        self.pos55 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos55.setGeometry(QtCore.QRect(280, 280, 41, 41))
        self.pos55.setFont(font)
        self.pos55.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos55.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos55.setObjectName("pos55")

        self.pos34 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos34.setGeometry(QtCore.QRect(240, 200, 41, 41))
        self.pos34.setFont(font)
        self.pos34.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos34.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos34.setObjectName("pos34")

        self.pos44 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos44.setGeometry(QtCore.QRect(240, 240, 41, 41))
        self.pos44.setFont(font)
        self.pos44.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos44.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos44.setObjectName("pos44")

        self.pos46 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos46.setGeometry(QtCore.QRect(330, 240, 41, 41))
        self.pos46.setFont(font)
        self.pos46.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos46.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos46.setObjectName("pos46")

        self.pos48 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos48.setGeometry(QtCore.QRect(410, 240, 41, 41))
        self.pos48.setFont(font)
        self.pos48.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos48.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos48.setObjectName("pos48")

        self.pos38 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos38.setGeometry(QtCore.QRect(410, 200, 41, 41))
        self.pos38.setFont(font)
        self.pos38.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos38.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos38.setObjectName("pos38")

        self.pos36 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos36.setGeometry(QtCore.QRect(330, 200, 41, 41))
        self.pos36.setFont(font)
        self.pos36.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos36.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos36.setObjectName("pos36")

        self.pos57 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos57.setGeometry(QtCore.QRect(370, 280, 41, 41))
        self.pos57.setFont(font)
        self.pos57.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos57.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos57.setObjectName("pos57")

        self.pos56 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos56.setGeometry(QtCore.QRect(330, 280, 41, 41))
        self.pos56.setFont(font)
        self.pos56.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos56.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos56.setObjectName("pos56")

        self.pos58 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos58.setGeometry(QtCore.QRect(410, 280, 41, 41))
        self.pos58.setFont(font)
        self.pos58.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos58.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos58.setObjectName("pos58")

        self.pos37 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos37.setGeometry(QtCore.QRect(370, 200, 41, 41))
        self.pos37.setFont(font)
        self.pos37.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos37.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos37.setObjectName("pos37")

        self.pos47 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos47.setGeometry(QtCore.QRect(370, 240, 41, 41))
        self.pos47.setFont(font)
        self.pos47.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos47.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos47.setObjectName("pos47")

        self.pos70 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos70.setGeometry(QtCore.QRect(70, 370, 41, 41))
        self.pos70.setFont(font)
        self.pos70.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos70.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos70.setObjectName("pos70")

        self.pos72 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos72.setGeometry(QtCore.QRect(150, 370, 41, 41))
        self.pos72.setFont(font)
        self.pos72.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos72.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos72.setObjectName("pos72")

        self.pos62 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos62.setGeometry(QtCore.QRect(150, 330, 41, 41))
        self.pos62.setFont(font)
        self.pos62.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos62.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos62.setObjectName("pos62")

        self.pos60 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos60.setGeometry(QtCore.QRect(70, 330, 41, 41))
        self.pos60.setFont(font)
        self.pos60.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos60.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos60.setObjectName("pos60")

        self.pos81 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos81.setGeometry(QtCore.QRect(110, 410, 41, 41))
        self.pos81.setFont(font)
        self.pos81.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos81.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos81.setObjectName("pos81")

        self.pos80 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos80.setGeometry(QtCore.QRect(70, 410, 41, 41))
        self.pos80.setFont(font)
        self.pos80.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos80.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos80.setObjectName("pos80")

        self.pos82 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos82.setGeometry(QtCore.QRect(150, 410, 41, 41))
        self.pos82.setFont(font)
        self.pos82.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos82.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos82.setObjectName("pos82")

        self.pos61 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos61.setGeometry(QtCore.QRect(110, 330, 41, 41))
        self.pos61.setFont(font)
        self.pos61.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos61.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos61.setObjectName("pos61")

        self.pos71 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos71.setGeometry(QtCore.QRect(110, 370, 41, 41))
        self.pos71.setFont(font)
        self.pos71.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos71.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos71.setObjectName("pos71")

        self.pos73 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos73.setGeometry(QtCore.QRect(200, 370, 41, 41))
        self.pos73.setFont(font)
        self.pos73.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos73.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos73.setObjectName("pos73")

        self.pos75 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos75.setGeometry(QtCore.QRect(280, 370, 41, 41))
        self.pos75.setFont(font)
        self.pos75.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos75.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos75.setObjectName("pos75")

        self.pos65 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos65.setGeometry(QtCore.QRect(280, 330, 41, 41))
        self.pos65.setFont(font)
        self.pos65.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos65.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos65.setObjectName("pos65")

        self.pos63 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos63.setGeometry(QtCore.QRect(200, 330, 41, 41))
        self.pos63.setFont(font)
        self.pos63.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos63.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos63.setObjectName("pos63")

        self.pos84 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos84.setGeometry(QtCore.QRect(240, 410, 41, 41))
        self.pos84.setFont(font)
        self.pos84.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos84.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos84.setObjectName("pos84")

        self.pos83 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos83.setGeometry(QtCore.QRect(200, 410, 41, 41))
        self.pos83.setFont(font)
        self.pos83.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos83.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos83.setObjectName("pos83")

        self.pos85 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos85.setGeometry(QtCore.QRect(280, 410, 41, 41))
        self.pos85.setFont(font)
        self.pos85.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos85.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos85.setObjectName("pos85")

        self.pos64 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos64.setGeometry(QtCore.QRect(240, 330, 41, 41))
        self.pos64.setFont(font)
        self.pos64.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos64.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos64.setObjectName("pos64")

        self.pos74 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos74.setGeometry(QtCore.QRect(240, 370, 41, 41))
        self.pos74.setFont(font)
        self.pos74.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos74.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos74.setObjectName("pos74")

        self.pos76 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos76.setGeometry(QtCore.QRect(330, 370, 41, 41))
        self.pos76.setFont(font)
        self.pos76.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos76.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos76.setObjectName("pos76")

        self.pos78 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos78.setGeometry(QtCore.QRect(410, 370, 41, 41))
        self.pos78.setFont(font)
        self.pos78.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos78.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos78.setObjectName("pos78")

        self.pos68 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos68.setGeometry(QtCore.QRect(410, 330, 41, 41))
        self.pos68.setFont(font)
        self.pos68.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos68.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos68.setObjectName("pos68")

        self.pos66 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos66.setGeometry(QtCore.QRect(330, 330, 41, 41))
        self.pos66.setFont(font)
        self.pos66.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos66.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos66.setObjectName("pos66")

        self.pos87 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos87.setGeometry(QtCore.QRect(370, 410, 41, 41))
        self.pos87.setFont(font)
        self.pos87.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos87.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos87.setObjectName("pos87")

        self.pos86 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos86.setGeometry(QtCore.QRect(330, 410, 41, 41))
        self.pos86.setFont(font)
        self.pos86.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos86.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos86.setObjectName("pos86")

        self.pos88 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos88.setGeometry(QtCore.QRect(410, 410, 41, 41))
        self.pos88.setFont(font)
        self.pos88.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos88.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos88.setObjectName("pos88")

        self.pos67 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos67.setGeometry(QtCore.QRect(370, 330, 41, 41))
        self.pos67.setFont(font)
        self.pos67.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos67.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos67.setObjectName("pos67")

        self.pos77 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pos77.setGeometry(QtCore.QRect(370, 370, 41, 41))
        self.pos77.setFont(font)
        self.pos77.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos77.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pos77.setObjectName("pos77")

#other elements
        #Solve Button
        self.solve_button = QtWidgets.QPushButton(self.centralwidget)
        self.solve_button.setGeometry(QtCore.QRect(510, 90, 151, 51))
        font.setPointSize(11)
        self.solve_button.setFont(font)
        self.solve_button.setObjectName("solve_button")

        #Title
        self.sudoku_board_tag = QtWidgets.QLabel(self.centralwidget)
        self.sudoku_board_tag.setGeometry(QtCore.QRect(170, 20, 171, 21))
        font.setPointSize(14)
        font.setWeight(50)
        self.sudoku_board_tag.setFont(font)
        self.sudoku_board_tag.setAlignment(QtCore.Qt.AlignCenter)
        self.sudoku_board_tag.setObjectName("sudoku_board_tag")

        #box
        self.saved_boards_box = QtWidgets.QGroupBox(self.centralwidget)
        self.saved_boards_box.setGeometry(QtCore.QRect(50, 490, 261, 151))
        font.setPointSize(10)
        self.saved_boards_box.setFont(font)
        self.saved_boards_box.setAlignment(QtCore.Qt.AlignCenter)
        self.saved_boards_box.setObjectName("saved_boards_box")

        #new board botton
        self.new_board_button = QtWidgets.QPushButton(self.saved_boards_box)
        self.new_board_button.setGeometry(QtCore.QRect(130, 90, 99, 30))
        self.new_board_button.setObjectName("new_board_button")

        #Sudoku board number tag
        self.sudoku_number = QtWidgets.QLabel(self.saved_boards_box)
        self.sudoku_number.setGeometry(QtCore.QRect(120, 30, 121, 53))
        self.sudoku_number.setAlignment(QtCore.Qt.AlignCenter)
        self.sudoku_number.setObjectName("sudoku_number")

        #radios
        font.setPointSize(10)
        self.hard_radio = QtWidgets.QRadioButton(self.saved_boards_box)
        self.hard_radio.setGeometry(QtCore.QRect(10, 100, 85, 22))
        self.hard_radio.setFont(font)
        self.hard_radio.setObjectName("hard_radio")

        self.medium_radio = QtWidgets.QRadioButton(self.saved_boards_box)
        self.medium_radio.setGeometry(QtCore.QRect(10, 70, 85, 22))
        self.medium_radio.setFont(font)
        self.medium_radio.setObjectName("medium_radio")

        self.easy_radio = QtWidgets.QRadioButton(self.saved_boards_box)
        self.easy_radio.setGeometry(QtCore.QRect(10, 40, 85, 22))
        self.easy_radio.setFont(font)
        self.easy_radio.setObjectName("easy_radio")

        #box
        font.setPointSize(10)
        self.results_box = QtWidgets.QGroupBox(self.centralwidget)
        self.results_box.setGeometry(QtCore.QRect(340, 510, 321, 111))
        self.results_box.setFont(font)
        self.results_box.setAlignment(QtCore.Qt.AlignCenter)
        self.results_box.setObjectName("results_box")

        #box
        font.setPointSize(11)
        self.solo_play_box = QtWidgets.QGroupBox(self.centralwidget)
        self.solo_play_box.setGeometry(QtCore.QRect(500, 230, 161, 231))
        self.solo_play_box.setFont(font)
        self.solo_play_box.setAlignment(QtCore.Qt.AlignCenter)
        self.solo_play_box.setObjectName("solo_play_box")

        #solo start button
        self.solo_start = QtWidgets.QPushButton(self.solo_play_box)
        self.solo_start.setGeometry(QtCore.QRect(10, 50, 141, 41))
        self.solo_start.setObjectName("solo_start")

        #solo check answer button
        self.solo_check_solution = QtWidgets.QPushButton(self.solo_play_box)
        self.solo_check_solution.setGeometry(QtCore.QRect(10, 110, 141, 41))
        self.solo_check_solution.setObjectName("solo_check_solution")

        #results time tag
        self.results_tag = QtWidgets.QLabel(self.results_box)
        self.results_tag.setGeometry(QtCore.QRect(10, 30, 291, 61))
        self.results_tag.setAlignment(QtCore.Qt.AlignCenter)
        self.results_tag.setWordWrap(True)
        self.results_tag.setObjectName("results_tag")

        #reset buttons
        font.setPointSize(9)
        self.solo_reset_button = QtWidgets.QPushButton(self.solo_play_box)
        self.solo_reset_button.setGeometry(QtCore.QRect(30, 180, 93, 28))
        self.solo_reset_button.setFont(font)
        self.solo_reset_button.setObjectName("solo_reset_button")

        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(540, 170, 93, 28))
        self.reset_button.setFont(font)
        self.reset_button.setObjectName("reset_button")

        #?
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sudoku Solver by Lucas H.T.M."))
        self.solve_button.setText(_translate("MainWindow", "Solve Board"))
        self.sudoku_board_tag.setText(_translate("MainWindow", "Sudoku Board"))
        self.saved_boards_box.setTitle(_translate("MainWindow", "Saved Boards"))
        self.new_board_button.setText(_translate("MainWindow", "New Board"))
        self.sudoku_number.setText(_translate("MainWindow", "Select a difficulty"))
        self.hard_radio.setText(_translate("MainWindow", "Hard"))
        self.medium_radio.setText(_translate("MainWindow", "Medium"))
        self.easy_radio.setText(_translate("MainWindow", "Easy"))
        self.solo_play_box.setTitle(_translate("MainWindow", "Play by Yourself"))
        self.solo_start.setText(_translate("MainWindow", "Start Playing"))
        self.solo_check_solution.setText(_translate("MainWindow", "Check Solution"))
        self.solo_reset_button.setText(_translate("MainWindow", "Partial Reset"))
        self.results_box.setTitle(_translate("MainWindow", "Results"))
        self.results_tag.setText(_translate("MainWindow", "It took Python and Numpy: X seconds to solve this Sudoku Board!"))
        self.reset_button.setText(_translate("MainWindosw", "Full Reset"))


